import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from "next/font/google";
import React from "react";
import 'react-phone-input-2/lib/style.css';
import "./globals.css";
import "./ReactToastify.css";
import ClientProvider from "./ClientProvider";

//TODO: Create a component that will render all the client side 
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext", "latin"],
  variable: "--font-poppins",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "First Event",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          poppins.variable,
          roboto_mono.variable,
          "overflow-x-hidden mx-auto font-sans h-full min-h-screen"
        )}
      >
        <ClientProvider>
          {children}
        </ClientProvider>

      </body>
    </html>
  );
}
