import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import React from "react";
import Footer from "@/app/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { cn } from "@/lib/utils";

const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "First Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(' ', poppins.className)}>
        <div className="pt-10 md:pt-0">
          {children}
        <ToastContainer position='bottom-right' theme="colored" autoClose={3000} />
        </div>
        <Footer />
      </body>
    </html>
  );
}
