import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import "./ReactToastify.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/partial/Footer";
import { ToastContainer } from "react-toastify";
import "react-phone-input-2/lib/style.css";
import StripeProvider from "./StripeProvider";
import { StoreProvider } from "@/store/StoreProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext", "latin"],
  variable: "--font-poppins",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "First Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={cn(
            poppins.variable,
            roboto_mono.variable,
            "overflow-x-hidden mx-auto font-sans h-full min-h-screen"
          )}
        >
          <StripeProvider>
            {children}
            <ToastContainer
              position="bottom-right"
              theme="colored"
              autoClose={3000}
            />
            <Footer />
          </StripeProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
